package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/elpic/archon/internal/standards"
)

// initCommand is split out so tests can call runInitCmd directly without
// re-parsing the flag set.
type initCommand struct {
	target string
	from   string
}

func runInit(_ context.Context, args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	from := fs.String("from", "", "org/repo to inherit standards from (e.g. elpic/go-standards)")
	target := fs.String("target", ".", "project path to initialize")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if *target == "" {
		return fmt.Errorf("init: --target must be non-empty")
	}
	if err := validateFrom(*from); err != nil {
		return err
	}
	return runInitCmd(initCommand{target: *target, from: *from})
}

// validateFrom enforces the owner/repo shape of the --from flag at the CLI
// boundary. Empty input is valid (means "no inheritance"). We delegate the
// actual character allow-list to standards.ValidateOrgRepo so a value that
// will be accepted here is guaranteed to be accepted at resolve time too.
func validateFrom(s string) error {
	if s == "" {
		return nil
	}
	if err := standards.ValidateOrgRepo(s); err != nil {
		return fmt.Errorf("init: --from must be in the form owner/repo, got %q", s)
	}
	return nil
}

// runInitCmd scaffolds .archon/standards.md in the target directory.
// It is idempotent: if the file already exists, the call is a no-op
// and no error is returned, so re-running is safe.
func runInitCmd(cmd initCommand) error {
	dir := filepath.Join(cmd.target, ".archon")
	file := filepath.Join(dir, "standards.md")

	// Idempotency: stat the file (not the directory). If the file
	// exists, do nothing.
	if _, err := os.Stat(file); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("init: stat %s: %w", file, err)
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("init: mkdir %s: %w", dir, err)
	}
	body := renderInitHeader(cmd.from)
	if err := os.WriteFile(file, []byte(body), 0o644); err != nil {
		return fmt.Errorf("init: write %s: %w", file, err)
	}
	return nil
}

// renderInitHeader produces the body of the .archon/standards.md file
// generated by `archon init`.
//
// With a `from` flag, the file is a redirect-only comment block. The
// resolver treats such a file as a tier-1 miss, which causes the audit
// pipeline to fetch the org's standards instead.
//
// Without a `from` flag, the file has a "# Project Standards" body that
// makes it tier-1 — the project file is the source of truth.
func renderInitHeader(from string) string {
	var b strings.Builder
	b.WriteString("<!--\n")
	b.WriteString("  Generated by `archon init`. Do not edit the `from:` line.\n")
	if from != "" {
		fmt.Fprintf(&b, "  from: %s\n", from)
	} else {
		b.WriteString("  Pass --from=owner/repo to inherit from an org source.\n")
	}
	b.WriteString("-->\n")

	if from == "" {
		b.WriteString("\n# Project Standards\n\n")
		b.WriteString("This file is the highest-priority tier in archon's resolution\n")
		b.WriteString("order. Add project-specific standards below.\n")
	} else {
		// With --from, the comment block is the entire file. The resolver
		// sees a redirect and fetches the org source. Adding a body
		// here would shadow the org and is intentionally omitted.
		b.WriteString("\n")
	}
	return b.String()
}

